name: Daily Email

on:
  push:
    branches:
      - master
  schedule:
    - cron: '15 10 * * *'

jobs:
  render-email:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1
      - name: Setup Environment
        uses: r-lib/actions/setup-renv@v1
      - name: Delete old email file
        continue-on-error: true
        run: |
          rm ./email.md
      - name: Render Rmarkdown files
        run: |
          install.packages('rmarkdown')
          install.packages('remotes')
          remotes::install_github("pbulsink/HockeyModel")
          rmarkdown::render("./email.Rmd")
        shell: Rscript {0}
      - name: Commit results
        if: success()
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add --all
          git commit -am 'Re-build Rmarkdown files'
          git push
      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Daily Game Odds Email $(date +'%Y-%m-%d')
          # Required recipients' addresses:
          to: ${{secrets.MAIL_RECIPIENT}}
          # Required sender full name (address can be skipped):
          from: ${{secrets.MAIL_FROM}}
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional HTML body read from file:
          html_body: file://email.md
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
